### ISSUE TITLE
Test errors when run in a 32 bit system

### ISSUE THREAD

**Issue by mapreri** [dprog-philippe-docourt/django-qr-code#19]
Hi,

when I tried to run the testsuite on a i386 system (but the same happened on armhf, but not arm64, so my guess is that it's bitness-related), I had the following errors:

```
python3.8 manage.py test
System check identified no issues (0 silenced).
....Unknown image format: invalid-image-format
.Testing template: {% qr_url_for_email "john.doe@domain.com" image_format="png" size="t" cache_enabled=False %}
Testing template: {% qr_url_for_tel  "+41769998877" image_format="png" size="t" cache_enabled=False %}
Testing template: {% qr_url_for_sms  "+41769998877" image_format="png" size="t" cache_enabled=False %}
Testing template: {% qr_url_for_geolocation latitude=586000.32 longitude=250954.19 altitude=500 image_format="png" size="t" cache_enabled=False %}
Testing template: {% qr_url_for_geolocation coordinates=coordinates image_format="png" size="t" cache_enabled=False %}
Testing template: {% qr_url_for_google_maps latitude=586000.32 longitude=250954.19 image_format="png" size="t" cache_enabled=False %}
Testing template: {% qr_url_for_google_maps coordinates=coordinates image_format="png" size="t" cache_enabled=False %}
Testing template: {% qr_url_for_wifi wifi_config image_format="png" size="t" cache_enabled=False %}
Testing template: {% qr_url_for_wifi wifi_config image_format="png" size="t" cache_enabled=False %}
Testing template: {% qr_url_for_wifi wifi_config=wifi_config image_format="png" size="t" cache_enabled=False %}
Testing template: {% qr_url_for_contact contact_detail image_format="png" size="t" cache_enabled=False %}
Testing template: {% qr_url_for_contact contact_detail image_format="png" size="t" cache_enabled=False %}
Testing template: {% qr_url_for_contact contact_detail=contact_detail image_format="png" size="t" cache_enabled=False %}
Testing template: {% qr_url_for_youtube "J9go2nj6b3M" image_format="png" size="t" cache_enabled=False %}
Testing template: {% qr_url_for_youtube video_id image_format="png" size="t" cache_enabled=False %}
Testing template: {% qr_url_for_google_play "ch.admin.meteoswiss" image_format="png" size="t" cache_enabled=False %}
.Testing template: {% qr_url_for_email "john.doe@domain.com" image_format="svg" cache_enabled=False %}
FTesting template: {% qr_for_email "john.doe@domain.com" image_format="png" size="t" %}
Testing template: {% qr_for_tel  "+41769998877" image_format="png" size="t" %}
Testing template: {% qr_for_sms  "+41769998877" image_format="png" size="t" %}
Testing template: {% qr_for_geolocation latitude=586000.32 longitude=250954.19 altitude=500 image_format="png" size="t" %}
Testing template: {% qr_for_geolocation coordinates=coordinates image_format="png" size="t" %}
Testing template: {% qr_for_google_maps latitude=586000.32 longitude=250954.19 image_format="png" size="t" %}
Testing template: {% qr_for_google_maps coordinates=coordinates image_format="png" size="t" %}
Testing template: {% qr_for_wifi wifi_config image_format="png" size="t" %}
Testing template: {% qr_for_wifi wifi_config image_format="png" size="t" %}
Testing template: {% qr_for_wifi wifi_config=wifi_config image_format="png" size="t" %}
Testing template: {% qr_for_contact contact_detail image_format="png" size="t" %}
Testing template: {% qr_for_contact contact_detail image_format="png" size="t" %}
Testing template: {% qr_for_contact contact_detail=contact_detail image_format="png" size="t" %}
Testing template: {% qr_for_youtube "J9go2nj6b3M" image_format="png" size="t" %}
Testing template: {% qr_for_youtube video_id image_format="png" size="t" %}
Testing template: {% qr_for_google_play "ch.admin.meteoswiss" image_format="png" size="t" %}
.Testing template: {% qr_for_email "john.doe@domain.com" image_format="svg" %}
FTesting template: {% qr_from_text "/%+¼@#=<>àé" image_format="png" error_correction="L" %}
Testing template: {% qr_from_text "/%+¼@#=<>àé" image_format="png" error_correction="M" %}
Testing template: {% qr_from_text "/%+¼@#=<>àé" image_format="png" error_correction="Q" %}
Testing template: {% qr_from_text "/%+¼@#=<>àé" image_format="png" error_correction="H" %}
.Testing PNG with size t
Testing PNG with size T
Testing PNG with size s
Testing PNG with size S
Testing PNG with size None
Testing PNG with size -1
Testing PNG with size 0
Testing PNG with size m
Testing PNG with size M
Testing PNG with size l
Testing PNG with size L
Testing PNG with size h
Testing PNG with size H
Testing PNG with size 6
Testing PNG with size 6
Testing PNG with size 8
Testing PNG with size 8
Testing PNG with size 10
Testing PNG with size 10
.Testing PNG with version None
Testing PNG with version -1
Testing PNG with version 0
Testing PNG with version 41
Testing PNG with version -1
Testing PNG with version 0
Testing PNG with version 41
Testing PNG with version blabla
Testing PNG with version 1
Testing PNG with version 1
Testing PNG with version 2
Testing PNG with version 2
Testing PNG with version 4
Testing PNG with version 4
.Testing template: {% qr_from_text "/%+¼@#=<>àé" image_format="svg" error_correction="L" %}
FTesting SVG with size t
Unknown image format: invalid-format-name
FTesting SVG with version None
Unknown image format: invalid-format-name
FTesting PNG URL with error correction: L
Testing PNG URL with error correction: M
Testing PNG URL with error correction: Q
Testing PNG URL with error correction: H
.	 - cache_enabled=True, url_signature_enabled=True
	 - cache_enabled=True, url_signature_enabled=False
	 - cache_enabled=True, url_signature_enabled=None
	 - cache_enabled=False, url_signature_enabled=True
	 - cache_enabled=False, url_signature_enabled=False
	 - cache_enabled=False, url_signature_enabled=None
	 - cache_enabled=None, url_signature_enabled=True
	 - cache_enabled=None, url_signature_enabled=False
	 - cache_enabled=None, url_signature_enabled=None
.	 - cache_enabled=True, url_signature_enabled=True
	 - cache_enabled=True, url_signature_enabled=False
	 - cache_enabled=True, url_signature_enabled=None
	 - cache_enabled=False, url_signature_enabled=True
	 - cache_enabled=False, url_signature_enabled=False
	 - cache_enabled=False, url_signature_enabled=None
	 - cache_enabled=None, url_signature_enabled=True
	 - cache_enabled=None, url_signature_enabled=False
	 - cache_enabled=None, url_signature_enabled=None
.	 - cache_enabled=True, url_signature_enabled=True
	 - cache_enabled=True, url_signature_enabled=False
	 - cache_enabled=True, url_signature_enabled=None
	 - cache_enabled=False, url_signature_enabled=True
	 - cache_enabled=False, url_signature_enabled=False
	 - cache_enabled=False, url_signature_enabled=None
	 - cache_enabled=None, url_signature_enabled=True
	 - cache_enabled=None, url_signature_enabled=False
	 - cache_enabled=None, url_signature_enabled=None
.Testing SVG URL with error correction: L
Unknown image format: invalid-format-name
F	 - cache_enabled=True, url_signature_enabled=True, user=None
Unknown image format: invalid-format-name
F	 - cache_enabled=True, url_signature_enabled=True, user=None
Unknown image format: invalid-format-name
F.	 - cache_enabled=True, url_signature_enabled=True, user=None
Unknown image format: invalid-format-name
F	 - cache_enabled=True, url_signature_enabled=True, user=None
Unknown image format: invalid-format-name
F	 - cache_enabled=True, url_signature_enabled=True, user=None
Unknown image format: invalid-format-name
F	 - cache_enabled=True, url_signature_enabled=True, user=None
Unknown image format: invalid-format-name
F....
======================================================================
FAIL: test_demo_sample_urls_in_svg_format (qr_code.tests.tests.TestQRForApplications)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/django-qr-code-1.3.1/qr_code/tests/tests.py", line 609, in test_demo_sample_urls_in_svg_format
    self.assertEqual(source_image_data, ref_image_data)
AssertionError: '<?xm[221 chars]d="M 16.2 39.6 L 16.2 41.4 L 18.0 41.4 L 18.0 [16102 chars]svg>' != '<?xm[221 chars]d="M 34.2 45 L 34.2 46.8 L 36.0 46.8 L 36.0 45[16102 chars]svg>'
Diff is 32712 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_demo_samples_embedded_in_svg_format (qr_code.tests.tests.TestQRForApplications)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/django-qr-code-1.3.1/qr_code/tests/tests.py", line 586, in test_demo_samples_embedded_in_svg_format
    self.assertEqual(source_image_data, ref_image_data)
AssertionError: '<?xm[221 chars]d="M 16.2 39.6 L 16.2 41.4 L 18.0 41.4 L 18.0 [16102 chars]svg>' != '<?xm[221 chars]d="M 34.2 45 L 34.2 46.8 L 36.0 46.8 L 36.0 45[16102 chars]svg>'
Diff is 32712 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_error_correction (qr_code.tests.tests.TestQRFromTextSvgResult)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/django-qr-code-1.3.1/qr_code/tests/tests.py", line 429, in test_error_correction
    self.assertEqual(source_image_data, ref_image_data)
AssertionError: '<svg[177 chars]d="M 39.6 7.2 L 39.6 9.0 L 41.4 9.0 L 41.4 7.2[10480 chars]svg>' != '<svg[177 chars]d="M 28.8 14.4 L 28.8 16.2 L 30.6 16.2 L 30.6 [10480 chars]svg>'
Diff is 21429 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_size (qr_code.tests.tests.TestQRFromTextSvgResult)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/django-qr-code-1.3.1/qr_code/tests/tests.py", line 381, in test_size
    self.assertEqual(qr1, result)
AssertionError: '<svg[177 chars]d="M 13.2 2.4 L 13.2 3.0 L 13.8 3.0 L 13.8 2.4[9506 chars]svg>' != '<svg[177 chars]d="M 9.6 4.8 L 9.6 5.4 L 10.2 5.4 L 10.2 4.8 z[9506 chars]svg>'

======================================================================
FAIL: test_version (qr_code.tests.tests.TestQRFromTextSvgResult)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/django-qr-code-1.3.1/qr_code/tests/tests.py", line 411, in test_version
    self.assertEqual(qr1, result)
AssertionError: '<svg[177 chars]d="M 39.6 7.2 L 39.6 9.0 L 41.4 9.0 L 41.4 7.2[10434 chars]svg>' != '<svg[177 chars]d="M 28.8 14.4 L 28.8 16.2 L 30.6 16.2 L 30.6 [10434 chars]svg>'

======================================================================
FAIL: test_svg_error_correction (qr_code.tests.tests.TestQRUrlFromTextResult)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/django-qr-code-1.3.1/qr_code/tests/tests.py", line 326, in test_svg_error_correction
    self.assertEqual(source_image_data, ref_image_data)
AssertionError: '<svg[177 chars]d="M 39.6 7.2 L 39.6 9.0 L 41.4 9.0 L 41.4 7.2[10480 chars]svg>' != '<svg[177 chars]d="M 28.8 14.4 L 28.8 16.2 L 30.6 16.2 L 30.6 [10480 chars]svg>'
Diff is 21429 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_svg_url (qr_code.tests.tests.TestQRUrlFromTextResult)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/django-qr-code-1.3.1/qr_code/tests/tests.py", line 189, in test_svg_url
    self.assertEqual(image_data, TestQRUrlFromTextResult._get_reference_result_for_default_svg())
AssertionError: '<?xm[217 chars]d="M 2.2 0.4 L 2.2 0.5 L 2.3 0.5 L 2.3 0.4 z M[8979 chars]svg>' != '<?xm[217 chars]d="M 1.6 0.8 L 1.6 0.9 L 1.7 0.9 L 1.7 0.8 z M[8979 chars]svg>'
Diff is 18458 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_svg_with_cache_but_no_alias (qr_code.tests.tests.TestQRUrlFromTextResult)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/test/utils.py", line 373, in inner
    return func(*args, **kwargs)
  File "/build/django-qr-code-1.3.1/qr_code/tests/tests.py", line 228, in test_svg_with_cache_but_no_alias
    self.test_svg_url()
  File "/build/django-qr-code-1.3.1/qr_code/tests/tests.py", line 189, in test_svg_url
    self.assertEqual(image_data, TestQRUrlFromTextResult._get_reference_result_for_default_svg())
AssertionError: '<?xm[217 chars]d="M 2.2 0.4 L 2.2 0.5 L 2.3 0.5 L 2.3 0.4 z M[8979 chars]svg>' != '<?xm[217 chars]d="M 1.6 0.8 L 1.6 0.9 L 1.7 0.9 L 1.7 0.8 z M[8979 chars]svg>'
Diff is 18458 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_url_with_protection_settings_1 (qr_code.tests.tests.TestQRUrlFromTextResult)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/test/utils.py", line 373, in inner
    return func(*args, **kwargs)
  File "/build/django-qr-code-1.3.1/qr_code/tests/tests.py", line 242, in test_url_with_protection_settings_1
    self.test_svg_url()
  File "/build/django-qr-code-1.3.1/qr_code/tests/tests.py", line 189, in test_svg_url
    self.assertEqual(image_data, TestQRUrlFromTextResult._get_reference_result_for_default_svg())
AssertionError: '<?xm[217 chars]d="M 2.2 0.4 L 2.2 0.5 L 2.3 0.5 L 2.3 0.4 z M[8979 chars]svg>' != '<?xm[217 chars]d="M 1.6 0.8 L 1.6 0.9 L 1.7 0.9 L 1.7 0.8 z M[8979 chars]svg>'
Diff is 18458 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_url_with_protection_settings_2 (qr_code.tests.tests.TestQRUrlFromTextResult)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/test/utils.py", line 373, in inner
    return func(*args, **kwargs)
  File "/build/django-qr-code-1.3.1/qr_code/tests/tests.py", line 250, in test_url_with_protection_settings_2
    self.test_svg_url()
  File "/build/django-qr-code-1.3.1/qr_code/tests/tests.py", line 189, in test_svg_url
    self.assertEqual(image_data, TestQRUrlFromTextResult._get_reference_result_for_default_svg())
AssertionError: '<?xm[217 chars]d="M 2.2 0.4 L 2.2 0.5 L 2.3 0.5 L 2.3 0.4 z M[8979 chars]svg>' != '<?xm[217 chars]d="M 1.6 0.8 L 1.6 0.9 L 1.7 0.9 L 1.7 0.8 z M[8979 chars]svg>'
Diff is 18458 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_url_with_protection_settings_3 (qr_code.tests.tests.TestQRUrlFromTextResult)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/test/utils.py", line 373, in inner
    return func(*args, **kwargs)
  File "/build/django-qr-code-1.3.1/qr_code/tests/tests.py", line 259, in test_url_with_protection_settings_3
    self.test_svg_url()
  File "/build/django-qr-code-1.3.1/qr_code/tests/tests.py", line 189, in test_svg_url
    self.assertEqual(image_data, TestQRUrlFromTextResult._get_reference_result_for_default_svg())
AssertionError: '<?xm[217 chars]d="M 2.2 0.4 L 2.2 0.5 L 2.3 0.5 L 2.3 0.4 z M[8979 chars]svg>' != '<?xm[217 chars]d="M 1.6 0.8 L 1.6 0.9 L 1.7 0.9 L 1.7 0.8 z M[8979 chars]svg>'
Diff is 18458 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_url_with_protection_settings_4 (qr_code.tests.tests.TestQRUrlFromTextResult)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/test/utils.py", line 373, in inner
    return func(*args, **kwargs)
  File "/build/django-qr-code-1.3.1/qr_code/tests/tests.py", line 268, in test_url_with_protection_settings_4
    self.test_svg_url()
  File "/build/django-qr-code-1.3.1/qr_code/tests/tests.py", line 189, in test_svg_url
    self.assertEqual(image_data, TestQRUrlFromTextResult._get_reference_result_for_default_svg())
AssertionError: '<?xm[217 chars]d="M 2.2 0.4 L 2.2 0.5 L 2.3 0.5 L 2.3 0.4 z M[8979 chars]svg>' != '<?xm[217 chars]d="M 1.6 0.8 L 1.6 0.9 L 1.7 0.9 L 1.7 0.8 z M[8979 chars]svg>'
Diff is 18458 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 31 tests in 1.726s

FAILED (failures=12)
```

I haven't debugged this in any way, but any help or hint is appreciated!

**Comment by philippe-docourt** [comment]
I noticed similar instabilities of qrcode library when generating QR codes in SVG format under Python <= 3.6. The master branch of django-qr-code no longer use qrcode. It has been replaced by Segno.

Could you please indicate what version of django-qr-code and Python you are using?

**Comment by mapreri** [comment]
that's python3.8 (as written at the top of the paste), but I had the same errors with python3.9.   django-qr-code 1.3.1.

**Comment by philippe-docourt** [comment]
It appears that I'm able to reproduce the issue. The SVG generated on Ubuntu 18.04 i386 in my case do not match the ones that are used as references in the test folder.

However, even though the SVG structure is not the same, a partial check seems to indicate that the QR codes contain the correct data. So it might be all false negative. Moreover, the current version on master branch do not suffer from this problem*.

* There are however 2 UnicodeEncodeError happening on 32-bit system.

**Comment by philippe-docourt** [comment]
Fix will be available in version 2.0.

**Comment by mapreri** [comment]
Very well, thank you!!

Do you have any rough estimate as to when that will be released?

**Comment by philippe-docourt** [comment]
It is available right now [on PyPi](https://pypi.org/project/django-qr-code/2.0.0/)!

**Comment by mapreri** [comment]
Thank you!!  In a first test it seems to work perfectly indeed :)
